Los módulos o librerias son funciones que han escrito otras personas o compañias y que se piueden usar gratuitamente, incluso yo puedo crear un módulo y compartirlo.

In [ ]:
# El primer módulo que vamos a importar es el os, que me permite navegar como si estuviese en una consola de comandos
import os

In [ ]:
# Para ver donde estoy dentro de la carpeta
os.getcwd()

'/content'

In [ ]:
# Para ver que hay en el contenido o en mis carpetas uso el siguiente metodo
os.listdir()

['.config', 'gdrive', 'sample_data']

In [ ]:
#Para crear una nueva carpeta uso el método siguiente
os.makedirs("Carpeta mia")

In [ ]:
os.listdir()

['.config', 'Carpeta mia', 'gdrive', 'sample_data']

Para poder usar dataframe  vamos a usar dos bibliotecas, una de ellas es numpy y la otra es pandas, las dos se complementan y, hacen cosas diferentes.Para crear dataframe existen varias posibilidades, sin embargo, la más usada es la lectura directa desde un archivo.

In [ ]:
import pandas as pd #Importo pansas y le pongo el sobrenombre pd
import numpy as np #Importo numpay y le pongo el sobrenombre np

In [ ]:
# La primera forma de crear un dataframe es usando el metodo array, y luego guardarlo en una variable.
dataframe_1= np.array([[2,4],[6,8],[10,12],[14,16]])

In [ ]:
#Para crear el dataframe del arreglo anterior, debemos usar pandas
pd.DataFrame(dataframe_1)

    0   1
0   2   4
1   6   8
2  10  12
3  14  16

In [ ]:
dataframe_2= np.array([[3,6,9],[12,15,18],[21,24,27],[30,33,36]])

In [ ]:
pd.DataFrame(dataframe_2)

    0   1   2
0   3   6   9
1  12  15  18
2  21  24  27
3  30  33  36

In [ ]:
#Ahora vamos a cambiarle el nombre a las columnas, esto se hace de la siguiente manera
df1=pd.DataFrame(dataframe_1, index=["fila1","fila2","fila3","fila4"],
                 columns=["columna1","columna2"])

In [ ]:
df1

       columna1  columna2
fila1         2         4
fila2         6         8
fila3        10        12
fila4        14        16

Opción 2

In [ ]:
#Ahora creamos un dataframe usando listas
dataframe_3=[(2,4),(6,8),(10,12)]

In [ ]:
df3=pd.DataFrame(dataframe_3, index=["fila1","fila2","fila3"],
                     columns=["columna1","columna2"])

In [ ]:
df3

       columna1  columna2
fila1         2         4
fila2         6         8
fila3        10        12

In [ ]:
#Ahora creamos un dataframe usando listas
dataframe_lista=[("Karen","Lagos",24),("Carlos", "Lagos",61),("Liliana","Bautista",54),("Hortencia","Lagos",79),("Angie","Lagos",30),("Camilo","Bautista",30)]

In [ ]:
df4=pd.DataFrame(dataframe_lista, index=["1","2","3","4","5","6"],
                     columns=["Nombre","Apellido","Edad"])

In [ ]:
df4

      Nombre  Apellido  Edad
1      Karen     Lagos    24
2     Carlos     Lagos    61
3    Liliana  Bautista    54
4  Hortencia     Lagos    79
5      Angie     Lagos    30
6     Camilo  Bautista    30

In [ ]:
#Primero creamos dos listas puedo crear cuantas listas quiera, entiendo que las listas son las columnas del dataframe
ciudadColombia=["Bogotá","Medellin","Cali","Barranquilla"]
ciudadesInfo=[11000000,2500000,2300000,1300000]

In [ ]:
#Ahora creamos los diccionarios de las listas
ciudades={"ciudades":ciudadColombia,"población":ciudadesInfo}

In [ ]:
#Le paso el metodo de pandas
df5=pd.DataFrame(ciudades)

In [ ]:
#llamo el Dataframe
df5

       ciudades  población
0        Bogotá   11000000
1      Medellin    2500000
2          Cali    2300000
3  Barranquilla    1300000

In [ ]:
#Hacer dataframe de 4 filas por 3 columnas de 4 paises
paisesMundo=["Colombia","Estados Unidos","Italia","Turquia"]
poblacionMundo=[51000000,335893238,58990000,86224025]
expectativavidaMundo=[73,81,84,77]

In [ ]:
paises={"paises":paisesMundo,"población":poblacionMundo,"expectativa":expectativavidaMundo}

In [ ]:
df6=pd.DataFrame(paises)

In [ ]:
df6

           paises  población  expectativa
0        Colombia   51000000           73
1  Estados Unidos  335893238           81
2          Italia   58990000           84
3         Turquia   86224025           77

Opción 4. Esta es la maneta en que se suben dataframe constantemente, porque nos permite realizar trabajos mas robustos con poco codigo.

In [ ]:
#usamos el metodo read de pandas para leer el arcivo csv
estudiantes=pd.read_csv("/content/gdrive/MyDrive/Python_Curso/StudentsPerformance (1).csv")

In [ ]:
estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
#Para mostrar las 5 primeras columnas
estudiantes.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
#Para mostrar las ultimas filas uso tail
estudiantes.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
#Mostrar en el encabezado las que yo determine
estudiantes.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [ ]:
#Para mostrar el tamaño del dataframe puedo utilizar el atributo shape
estudiantes.shape

(1000, 8)

In [ ]:
#Para mostrar cuantas columnas quiera uso head
estudiantes.head(60)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10

In [ ]:
#METODOS DE PANDAS

In [ ]:
#Para ver el tamaño y salto de los datos puedo utilizar el metodo index
estudiantes.index

RangeIndex(start=0, stop=1000, step=1)

In [ ]:
#Para ver las columnas
estudiantes.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
#para ver el tipo de dato de las columnas uso dtypes
estudiantes.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [ ]:
#Para obtener la informacion de todo el dataframe isamos el metodo info
estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
#Las medidas de tendencia central de todo el dataframe
estudiantes.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
#funciones de pandas
len(estudiantes)

1000

In [ ]:
max(estudiantes)

'writing score'

In [ ]:
max(estudiantes.index)

999

In [ ]:
type(estudiantes)

pandas.core.frame.DataFrame

In [ ]:
estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
round(estudiantes)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
#Para mostrar solo una columna lo hago de la siguiente manera
estudiantes["gender"]

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [ ]:
estudiantes["math score"]

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [ ]:
#para mostrar los datos de una sola columna
estudiantes["gender"].index

RangeIndex(start=0, stop=1000, step=1)

In [ ]:
estudiantes["gender"].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [ ]:
#La otra manera de mostrar una columna es usando el nombre directamente metodo
estudiantes.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [ ]:
#para elegir dos o mas columnas
estudiantes[["math score","reading score"]]

     math score  reading score
0            72             72
1            69             90
2            90             95
3            47             57
4            76             78
..          ...            ...
995          88             99
996          62             55
997          59             71
998          68             78
999          77             86

[1000 rows x 2 columns]

**EJERCICIO 1 - ARCHIVO CSV**

In [ ]:
ejercicio=pd.read_csv("/content/gdrive/MyDrive/Python_Curso/Location_v3.csv")

In [ ]:
ejercicio

,locationIdentifier,locationType,locationName,address1,address2,city,postalCode,stateProvince,country,coordinates,includeInCorrelation,geo,sourceLink
0,LT-1,OPERATIONS,LightTree Plant 1 Birmingham,451 24th St N,NaN,Birmingham,35203,AL,USA,"33.5206608, -86.80249",True,AMERICAS,http://lighttree.com/LT-1
1,LT-2,OPERATIONS,LightTree Plant 2 Tuscaloosa,2436 University Blvd,NaN,Tuscaloosa,35401,AL,USA,"33.2098407, -87.5691735",True,AMERICAS,http://lighttree.com/LT-2
2,Alumi-lux - Nashua,SUPPLIER,Alumi-lux Metal Products - Nashua,5 Main St,NaN,Nashua,3064,NH,USA,"42.7653662, -71.467566",True,AMERICAS,http://lighttree.com/Alumi-lux - Nashua
3,Amos - Philadelphia,SUPPLIER,Amos Wire Products Inc - Philadelphia,1500 PA-3,NaN,Philadelphia,19102,PA,USA,"39.9525839, -75.1652215",True,AMERICAS,http://lighttree.com/Amos - Philadelphia
4,Autonomic - Morgantown,SUPPLIER,Autonomic Specialties - Morgantown,341-349 Oakland St,NaN,Morgantown,26505,WV,USA,"39.6478662, -79.966415",True,AMERICAS,http://lighttree.com/Autonomic - Morgantown
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,MAHD - Boston,CUSTOMER,Massachusetts Highway Department (Mass Highway...,1 Cambridge St,NaN,Boston,2114,MA,USA,"42.3600825, -71.0588801",True,AMERICAS,http://lighttree.com/MAHD - Boston
60,KYTC - Lexington,CUSTOMER,Kentucky Transportation Cabinet (KYTC) - Lexin...,404 S Limestone,NaN,Lexington,40508,KY,USA,"38.0405837, -84.5037164",True,AMERICAS,http://lighttree.com/KYTC - Lexington
61,NYDOT - New Rochelle,CUSTOMER,New York Department of Transportation - New Ro...,260 North Ave,NaN,New Rochelle,10801,NY,USA,"40.9114882, -73.7823549",True,AMERICAS,http://lighttree.com/NYDOT - New Rochelle
62,CALTRAN - San Diego,CUSTOMER,California Department of Transportation (Caltr...,402w Broadway,NaN,San Diego,92101,CA,USA,"32.715738, -117.1610838",True,AMERICAS,http://lighttree.com/CALTRAN - San Diego
63,AHTD - Bentonville,CUSTOMER,Arkansas State Highway and Transportation Dept...,100-198 N Main St,NaN,Bentonville,72712,AR,USA,"36.3728538, -94.2088172",True,AMERICAS,http://lighttree.com/AHTD - Bentonville

In [ ]:
ejercicio.head() #Para mostrar las 5 primeras columnas

,locationIdentifier,locationType,locationName,address1,address2,city,postalCode,stateProvince,country,coordinates,includeInCorrelation,geo,sourceLink
0,LT-1,OPERATIONS,LightTree Plant 1 Birmingham,451 24th St N,NaN,Birmingham,35203,AL,USA,"33.5206608, -86.80249",True,AMERICAS,http://lighttree.com/LT-1
1,LT-2,OPERATIONS,LightTree Plant 2 Tuscaloosa,2436 University Blvd,NaN,Tuscaloosa,35401,AL,USA,"33.2098407, -87.5691735",True,AMERICAS,http://lighttree.com/LT-2
2,Alumi-lux - Nashua,SUPPLIER,Alumi-lux Metal Products - Nashua,5 Main St,NaN,Nashua,3064,NH,USA,"42.7653662, -71.467566",True,AMERICAS,http://lighttree.com/Alumi-lux - Nashua
3,Amos - Philadelphia,SUPPLIER,Amos Wire Products Inc - Philadelphia,1500 PA-3,NaN,Philadelphia,19102,PA,USA,"39.9525839, -75.1652215",True,AMERICAS,http://lighttree.com/Amos - Philadelphia
4,Autonomic - Morgantown,SUPPLIER,Autonomic Specialties - Morgantown,341-349 Oakland St,NaN,Morgantown,26505,WV,USA,"39.6478662, -79.966415",True,AMERICAS,http://lighttree.com/Autonomic - Morgantown

In [ ]:
ejercicio.tail() #Para mostrar las ultimas filas uso tail

,locationIdentifier,locationType,locationName,address1,address2,city,postalCode,stateProvince,country,coordinates,includeInCorrelation,geo,sourceLink
59,MAHD - Boston,CUSTOMER,Massachusetts Highway Department (Mass Highway...,1 Cambridge St,NaN,Boston,2114,MA,USA,"42.3600825, -71.0588801",True,AMERICAS,http://lighttree.com/MAHD - Boston
60,KYTC - Lexington,CUSTOMER,Kentucky Transportation Cabinet (KYTC) - Lexin...,404 S Limestone,NaN,Lexington,40508,KY,USA,"38.0405837, -84.5037164",True,AMERICAS,http://lighttree.com/KYTC - Lexington
61,NYDOT - New Rochelle,CUSTOMER,New York Department of Transportation - New Ro...,260 North Ave,NaN,New Rochelle,10801,NY,USA,"40.9114882, -73.7823549",True,AMERICAS,http://lighttree.com/NYDOT - New Rochelle
62,CALTRAN - San Diego,CUSTOMER,California Department of Transportation (Caltr...,402w Broadway,NaN,San Diego,92101,CA,USA,"32.715738, -117.1610838",True,AMERICAS,http://lighttree.com/CALTRAN - San Diego
63,AHTD - Bentonville,CUSTOMER,Arkansas State Highway and Transportation Dept...,100-198 N Main St,NaN,Bentonville,72712,AR,USA,"36.3728538, -94.2088172",True,AMERICAS,http://lighttree.com/AHTD - Bentonville

In [ ]:
ejercicio.head(3) #Mostrar en el encabezado las que yo determine

,locationIdentifier,locationType,locationName,address1,address2,city,postalCode,stateProvince,country,coordinates,includeInCorrelation,geo,sourceLink
0,LT-1,OPERATIONS,LightTree Plant 1 Birmingham,451 24th St N,NaN,Birmingham,35203,AL,USA,"33.5206608, -86.80249",True,AMERICAS,http://lighttree.com/LT-1
1,LT-2,OPERATIONS,LightTree Plant 2 Tuscaloosa,2436 University Blvd,NaN,Tuscaloosa,35401,AL,USA,"33.2098407, -87.5691735",True,AMERICAS,http://lighttree.com/LT-2
2,Alumi-lux - Nashua,SUPPLIER,Alumi-lux Metal Products - Nashua,5 Main St,NaN,Nashua,3064,NH,USA,"42.7653662, -71.467566",True,AMERICAS,http://lighttree.com/Alumi-lux - Nashua

In [ ]:
ejercicio.shape #Para mostrar el tamaño del dataframe puedo utilizar el atributo shape

(64, 13)

In [ ]:
ejercicio.head(35) #Para mostrar cuantas columnas quiera uso head

,locationIdentifier,locationType,locationName,address1,address2,city,postalCode,stateProvince,country,coordinates,includeInCorrelation,geo,sourceLink
0,LT-1,OPERATIONS,LightTree Plant 1 Birmingham,451 24th St N,NaN,Birmingham,35203,AL,USA,"33.5206608, -86.80249",True,AMERICAS,http://lighttree.com/LT-1
1,LT-2,OPERATIONS,LightTree Plant 2 Tuscaloosa,2436 University Blvd,NaN,Tuscaloosa,35401,AL,USA,"33.2098407, -87.5691735",True,AMERICAS,http://lighttree.com/LT-2
2,Alumi-lux - Nashua,SUPPLIER,Alumi-lux Metal Products - Nashua,5 Main St,NaN,Nashua,3064,NH,USA,"42.7653662, -71.467566",True,AMERICAS,http://lighttree.com/Alumi-lux - Nashua
3,Amos - Philadelphia,SUPPLIER,Amos Wire Products Inc - Philadelphia,1500 PA-3,NaN,Philadelphia,19102,PA,USA,"39.9525839, -75.1652215",True,AMERICAS,http://lighttree.com/Amos - Philadelphia
4,Autonomic - Morgantown,SUPPLIER,Autonomic Specialties - Morgantown,341-349 Oakland St,NaN,Morgantown,26505,WV,USA,"39.6478662, -79.966415",True,AMERICAS,http://lighttree.com/Autonomic - Morgantown
5,Benchmark - Wheaton,SUPPLIER,Benchmark Lighting - Wheaton,2100 Willow Run,NaN,Wheaton,60189,IL,USA,"41.8461274, -88.1378685",True,AMERICAS,http://lighttree.com/Benchmark - Wheaton
6,Brewers - Phoenix,SUPPLIER,Brewers Manufacturing - Phoenix,22 W Washington St,NaN,Phoenix,85004,AZ,USA,"33.4483771, -112.0740373",True,AMERICAS,http://lighttree.com/Brewers - Phoenix
7,Core - Saranac Lake,SUPPLIER,Core Components of North America - Saranac Lake,272 Forest Hill Ave,NaN,Saranac Lake,12983,NY,USA,"44.329257, -74.116497",True,AMERICAS,http://lighttree.com/Core - Saranac Lake
8,Corporal - Tulsa,SUPPLIER,Corporal Brass - Tulsa,199 South Boulder Ave W,NaN,Tulsa,74103,OK,USA,"36.1539816, -95.992775",True,AMERICAS,http://lighttree.com/Corporal - Tulsa
9,EM - Hemphill,SUPPLIER,Engineered Materials - Hemphill,110 Market St,NaN,Hemphill,75948,TX,USA,"31.4325167, -93.8466981",True,AMERICAS,http://lighttree.com/EM - Hemphill
10,Exclusive - Billings,SUPPLIER,Exclusive Plastics - Billings,2417 I-90BL,NaN,Billings,59101,MT,USA,"45.7832856, -108.5006904",True,AMERICAS,http://lighttree.com/Exclusive - Billings
11,F & M - Columbus,SUPPLIER,F & M Metals - Columbus,37-39 US-33,NaN,Columbus,43215,OH,USA,"39.9611755, -82.9987942",True,AMERICAS,http://lighttree.com/F & M - Columbus
12,Flexilux - Worcester,SUPPLIER,Flexilux Industries - Worcester,455 Main St,NaN,Worcester,1608,MA,USA,"42.2625932, -71.8022934",True,AMERICAS,http://lighttree.com/Flexilux - Worcester
13,Gaylor - Ocean Springs,SUPPLIER,Gaylor Design - Ocean Springs,515 Washington Ave,NaN,Ocean Springs,39564,MS,USA,"30.4113097, -88.8278057",True,AMERICAS,http://lighttree.com/Gaylor - Ocean Springs
14,Gemini - Dallas,SUPPLIER,Gemini Design Technology - Dallas,1502 Marilla St,NaN,Dallas,75201,TX,USA,"32.7766642, -96.7969879",True,AMERICAS,http://lighttree.com/Gemini - Dallas
15,Glickman - Waterford,SUPPLIER,Glickman Lighting - Waterford,1218 Waterford Rd,NaN,Waterford,4088,ME,USA,"44.2117358, -70.682008",True,AMERICAS,http://lighttree.com/Glickman - Waterford
16,Groulsh - Charleston,SUPPLIER,Groulsh Industries - Charleston,201-299 Dickinson St,NaN,Charleston,25301,WV,USA,"38.3498195, -81.6326234",True,AMERICAS,http://lighttree.com/Groulsh - Charleston
17,Hardy - Salina,SUPPLIER,Hardy Industries - Salina,101-117 S 8th St,NaN,Salina,67401,KS,USA,"38.8402805, -97.6114237",True,AMERICAS,http://lighttree.com/Hardy - Salina
18,Holloway - Phoenix,SUPPLIER,Holloway Lighting Parts - Phoenix,4010 W Buckeye Rd,NaN,Phoenix,85009,AZ,USA,"33.4376, -112.146079",True,AMERICAS,http://lighttree.com/Holloway - Phoenix
19,Howard - Vineyard Haven,SUPPLIER,Howard Plastics - Vineyard Haven,6 Sumner Cir,NaN,Vineyard Haven,2568,MA,USA,"41.4403894, -70.6578064",True,AMERICAS,http://lighttree.com/Howard - Vineyard Haven
20,Interalloy - Bozeman,SUPPLIER,Interalloy Corporation - Bozeman,200-298 W Babcock St,NaN,Bozeman,59715,MT,USA,"45.677978, -111.040723",True,AMERICAS,http://lighttree.com/Interalloy - Bozeman
21,J&R - Montgomery,SUPPLIER,J&R Plastics - Montgomery,801-851 AL-21,NaN,Montgomery,36104,AL,USA,"32.3668052, -86.2999689",True,AMERICAS,http://lighttree.com/J&R - Montgomery
22,Lex - Ocean Pines,SUPPLIER,Lex Filters - Ocean Pines,212 Mumford Landing Rd,NaN,Ocean Pines,21811,MD,USA,"38.3885305, -75.1334013",True,AMERICAS,http://lighttree.com/Lex - Ocean Pines
23,LightLens - Ipswich,SUPPLIER,LightLens Industries - Ipswich,12 Brazier's Wood Rd,NaN,Ipswich,0RZ,IP3,UK,"52.0305506, 1.1865023",True,UKI,http://lighttree.com/LightLens - Ipswich
24,Litesource - San Antonio,SUPPLIER,Litesource Chrystal - San Antonio,1777 I- 410 Access Rd,NaN,San Antonio,78217,TX,USA,"29.5170299, -98.4364486",True,AMERICAS,http://lighttree.com/Litesource - San Antonio
25,Lorel - Sioux Falls,SUPPLIER,Lorel Lamps Parts - Sioux Falls,312 S Minnesota Ave,NaN,Sioux Falls,57104,SD,USA,"43.5445959, -96.7311034",True,AMERICAS,http://lighttree.com/Lorel - Sioux Falls
26,Luminar - Palm Beach Gardens,SUPPLIER,Luminar Lines - Palm Beach Gardens,411 4th Terrace,NaN,Palm Beach Gardens,33418,FL,USA,"26.8360229, -80.1342216",True,AMERICAS,http://lighttree.com/Luminar - Palm Beach Gardens
27,McGrey - Mt Sterling,SUPPLIER,McGrey Electrical - Mt Sterling,1221-1798 Cr-1024,NaN,Mt Sterling,40353,KY,USA,"38.0740561, -83.9073128",True,AMERICAS,http://lighttree.com/McGrey - Mt Sterling
28,Mueller - Pittsburgh,SUPPLIER,Mueller OEM - Pittsburgh,1101-1115 Wilhelm Ave,NaN,Pittsburgh,15236,PA,USA,"40.3252558, -79.9889288",True,AMERICAS,http://lighttree.com/Mueller - Pittsburgh
29,Paltronix - Wilmington,SUPPLIER,Paltronix - Wilmington,719 S 3rd St,NaN,Wilmington,28401,NC,USA,"34.2257255, -77.9447102",True,AMERICAS,http://lighttree.com/Paltronix - Wilmington
30,Plastico - Glen Allen,SUPPLIER,Plastico - Glen Allen,11699-11799 Bent Pine Rd,NaN,Glen Allen,23059,VA,USA,"37.6768619, -77.4853955",True,AMERICAS,http://lighttree.com/Plastico - Glen Allen
31,Plastilite - Scottsdale,SUPPLIER,Plastilite Corporation - Scottsdale,8000-8130 N 86th Pl,NaN,Scottsdale,85258,AZ,USA,"33.5541151, -111.8954292",True,AMERICAS,http://lighttree.com/Plastilite - Scottsdale
32,Plexilux - Springfield,SUPPLIER,Plexilux - Springfield,3636 S Campbell Ave,NaN,Springfield,65807,MO,USA,"37.1480273, -93.2946284",True,AMERICAS,http://lighttree.com/Plexilux - Springfield
33,Press - Albany,SUPPLIER,Press Lite Industries - Albany,48-56 Washington Ave,NaN,Albany,12210,NY,USA,"42.6525793, -73.7562317",True,AMERICAS,http://lighttree.com/Press - Albany
34,R&J - Vancouver,SUPPLIER,R&J Lamp Supply - Vancouver,16000 NE 22nd St,NaN,Vancouver,98684,WA,USA,"45.6388512, -122.5080781",True,AMERICAS,http://lighttree.com/R&J - Vancouver

In [ ]:
ejercicio.index #Para ver el tamaño y salto de los datos puedo utilizar el metodo index

RangeIndex(start=0, stop=64, step=1)

In [ ]:
ejercicio.columns #Para ver las columnas

Index(['locationIdentifier', 'locationType', 'locationName', 'address1',
       'address2', 'city', 'postalCode', 'stateProvince', 'country',
       'coordinates', 'includeInCorrelation', 'geo', 'sourceLink'],
      dtype='object')

In [ ]:
ejercicio.dtypes #para ver el tipo de dato de las columnas uso dtypes

locationIdentifier       object
locationType             object
locationName             object
address1                 object
address2                float64
city                     object
postalCode               object
stateProvince            object
country                  object
coordinates              object
includeInCorrelation       bool
geo                      object
sourceLink               object
dtype: object

In [ ]:
#Para obtener la informacion de todo el dataframe isamos el metodo info
estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/') #Para traer la carpeta de drive en Python

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).

**CLASE 18 OCTUBRE**

In [ ]:
#Para saber que tipo de dato es ese dataframe, uso la función type
type(estudiantes[["math score","reading score"]])

pandas.core.frame.DataFrame

In [ ]:
#Para mostrar mas de dos columnas puedo hacerlo con el mismo método
estudiantes[["math score","reading score"]]

     math score  reading score
0            72             72
1            69             90
2            90             95
3            47             57
4            76             78
..          ...            ...
995          88             99
996          62             55
997          59             71
998          68             78
999          77             86

[1000 rows x 2 columns]

In [ ]:
#Para crear columnas, existen dos formas, pero el metodo que mas se usa es como si estuviese llamando una columna.
#Vamos a crear una columna que nos muestre la nota de química
estudiantes["Score Chemistry"]=70
estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Score Chemistry
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

In [ ]:
#Tambien puedo crear valores aleatorios con un arreglo de numpy y luego usarlo para ponerlo en una columna nueva.
np.arange(0,1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [ ]:
len(np.arange(0,1000))

1000

In [ ]:
nota_quimica=np.arange(0,1000)
estudiantes["Score Chemistry"]=nota_quimica

In [ ]:
estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Score Chemistry
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [ ]:
#Asi puedo crear arreglos aleatorios que me dirvan para diligenciar la tabla
aleatorio=np.random.randint(1,100, size=1000) #creo 1000 numero aleatorios que vayan del 1 al 100

In [ ]:
estudiantes["Score Chemistry"]=aleatorio
estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Score Chemistry
0,female,group B,bachelor's degree,standard,none,72,72,74,20
1,female,group C,some college,standard,completed,69,90,88,90
2,female,group B,master's degree,standard,none,90,95,93,82
3,male,group A,associate's degree,free/reduced,none,47,57,44,88
4,male,group C,some college,standard,none,76,78,75,59
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,98
996,male,group C,high school,free/reduced,none,62,55,55,24
997,female,group C,high school,free/reduced,completed,59,71,65,12
998,female,group D,some college,standard,completed,68,78,77,46
999,female,group D,some college,free/reduced,none,77,86,86,71

In [ ]:
#Ahora si quisiera crear arreglos aleatorios pero con decimales, lo hago de la siguiente manera
np.random.uniform(1,100, size=1000)

array([31.7455259 ,  4.58005551, 94.44296505, 97.34197403, 36.7326204 ,
       83.9446577 , 17.36032491, 17.6350495 , 31.0782869 , 48.87832466,
       15.61558222, 48.67409859, 89.15678627, 63.9597893 , 46.68446512,
       70.07867503, 47.27719841, 80.8351802 , 80.71874766, 74.47848532,
       77.38051015, 20.77687827, 55.33704236, 21.82552719, 53.48157796,
       71.63080052, 78.93670683, 28.304114  , 96.1437264 , 22.46973346,
       76.91046254, 23.13304739, 18.15794591, 81.52641021,  9.7417134 ,
        9.29335587, 28.58980721, 35.47074424, 95.79324872, 58.54858168,
       19.9707132 ,  8.22036521, 77.09079151, 46.02757386, 88.91143118,
        3.80514502, 26.24915052, 40.37188084, 67.09912111, 13.33995819,
       30.41050044, 42.37968237, 88.40680869, 68.02561167, 30.86912951,
       60.58294955, 12.19381968, 47.23004898, 42.14090881, 32.33877711,
       78.69748083, 91.41164222, 15.38161269,  8.28460825, 13.31960387,
       56.38219122, 16.35779427, 60.11158752, 94.7079811 , 68.37676725,
       64.89416248, 16.94720959, 48.49149033, 29.69716906, 61.89122368,
       61.95522395, 37.44848573, 92.46632609, 77.06181511, 69.01240748,
       64.44869658, 20.22881824, 20.44930444, 47.05587255, 11.87874631,
        6.03458168, 14.9352209 , 48.76950082, 45.52077405, 63.19298677,
       43.9343733 , 20.54385733, 60.97103876,  9.70632155, 80.04092951,
       55.39878377, 36.39748767, 39.4099869 , 71.31642617, 68.93692673,
       42.40856795, 55.70740542, 40.04277913,  5.14734906, 68.57583981,
       72.03637998, 85.48904769, 13.05450488, 84.61141617,  8.27296004,
       24.43425802, 54.82517648, 88.70266737, 13.61284515,  5.07133076,
       73.01019422, 31.75796707, 48.69153236, 62.5699759 , 10.62582982,
       15.53267482, 24.24627247, 73.5521082 , 37.22703309, 77.09757356,
       40.47727173, 44.89478993,  7.03855671, 15.00179179, 57.69336581,
       99.58747625, 11.94690276, 56.09345679, 68.60574874, 96.11662657,
       37.60639979, 56.81125413, 90.22887526,  2.81711028, 17.26842804,
       25.75409707,  6.98717688, 98.64954376, 56.04102574, 36.71930374,
       59.53424608,  4.06251559, 67.07750667, 11.54820392, 57.04609046,
       82.16048631, 25.20819044, 55.05022126, 96.81588904,  6.43956601,
       95.40381885, 98.00411749, 13.50280353, 39.62435213, 23.98571243,
       27.4214834 , 66.88528892, 89.0413176 , 30.85976565, 60.65764145,
        7.81268256, 79.82355997, 77.62715515, 43.49611978, 62.25132922,
       44.39421239, 67.22200136, 79.43536888, 53.30838786, 33.20571803,
       66.17819594, 59.00692147, 81.06083237, 86.43338792, 50.49611771,
       47.33506834, 11.74192499, 58.2499639 ,  7.00298798, 28.26776899,
       24.1537352 , 21.20682753, 83.92873309,  8.21983758, 32.13127861,
        8.50842634, 82.94702322, 28.09022336, 63.93501979,  2.24091377,
       92.05037506,  5.70015721, 15.53048898, 39.62244115, 30.61249023,
       79.92547808, 26.74127652, 83.42291831, 57.09985786, 43.48553128,
       27.1895066 , 99.93697975, 98.72623251, 77.04459596, 96.05622248,
       77.15397063, 34.80198831, 30.64671205, 84.64080254, 93.1276349 ,
       27.78936449, 20.29502852, 37.80323875, 81.32277722, 28.4010866 ,
       60.0921678 , 66.5273596 , 58.35909097, 73.78157193,  4.43070561,
       95.99492661,  2.20007691, 73.01970327, 88.28829334, 51.45804266,
       76.26064346, 75.43114263, 97.84233583, 43.03332185, 65.40018204,
       38.89148774, 67.75035806, 80.93238996,  5.2606451 , 21.71612727,
        9.40887552, 45.70679982, 90.00652658, 50.37231817,  1.61239564,
       53.64004581, 67.42576652, 64.53187401, 76.43687029, 58.33706341,
       71.41780372, 81.86969969, 43.36387659,  4.71788599, 72.08808374,
       41.75360422, 98.34188497, 66.58210332, 39.26717386, 56.85880813,
       30.15167876,  6.82000273, 30.17191654, 19.63581925, 69.012294  ,
       34.85743502, 41.80499451, 80.24965342,  5.12041328, 61.30760052,
       85.31615472, 41.09919329, 56.84217302, 96.73791859, 73.59760744,
       45.45025265, 93.42468938, 85.5111445 , 65.09060253, 67.48083077,
       33.85002471, 39.71906172, 95.6826751 , 30.17236127, 69.55689024,
       45.12505424, 25.93342387, 52.10980495, 93.62206648, 73.5900393 ,
       51.45674173,  9.74984923, 34.32429989, 48.51620575, 84.08074619,
        9.53843035, 99.73542043, 83.36363677, 74.82391929, 20.54850918,
       63.45876618,  7.28485721, 87.25696661, 24.12765201, 24.67818741,
        6.23356538, 23.00612101,  4.05274734, 24.13753484, 55.04406436,
       15.21450543, 56.13973571,  6.09450413, 80.7937304 , 60.1333239 ,
       98.90725416, 45.30869377, 75.71928932, 27.9244489 , 35.08055217,
       88.8319159 , 32.41261627, 68.66831401, 48.21615948, 69.22070301,
        6.441544  , 78.71604791, 46.83886456, 96.17333739, 28.11355994,
       65.38246516,  4.7059061 , 11.95321013, 46.8101641 , 32.40738378,
       76.50302288, 99.96577568, 86.80453321,  5.53123614, 45.70856933,
       78.73051823, 31.03812609, 32.64290331, 40.48783556, 44.05360597,
       39.21638623, 13.90566633, 61.07491492, 81.4794783 , 78.1724616 ,
       95.03948658, 13.65425136, 11.68540391,  7.73110091, 14.07536174,
       68.08905985,  4.72309619, 42.00783268, 35.32394879, 78.37063216,
       15.77196643, 30.43852611, 84.508972  , 65.01315761, 23.99761204,
       72.25296315, 42.51814074, 58.61507739, 36.57797325, 25.80661213,
       74.50045555, 70.95775558, 19.88131238, 21.92259486, 10.76707573,
       33.78407047, 76.64680945, 43.09822277, 30.89002904, 24.06758613,
       70.62801801, 35.47004555, 78.38226614, 97.12636406, 92.81714514,
       78.48780278, 78.31425758, 78.59170622, 60.5003153 , 45.34311775,
       86.6265711 , 92.98433174, 81.54122761, 24.70314822, 82.83431856,
       46.39151088, 25.28660964, 96.91080849, 16.78400764,  8.66137507,
       33.14081696, 76.57865296, 94.24459246, 69.75124683, 92.14903775,
       85.12975013, 12.93675981, 78.73977309, 99.29322418, 24.58943095,
       43.66091301, 38.67248136, 26.87516764, 82.52792328, 24.37102115,
       53.40377549, 10.75750332, 38.16949135, 24.23019078, 93.18618944,
       46.89891502, 22.58624023, 80.86917164, 25.39186952, 32.28667829,
       48.65055759, 26.58837037, 77.73262058, 79.11803424, 73.38566915,
       58.14830672,  2.86822964, 73.18836193, 16.53970609, 94.94591255,
       46.60127444, 11.30436563, 60.27154637, 18.57285835, 65.45505562,
       42.11834904, 77.26534916, 20.00563454, 28.25684234, 90.1422775 ,
       59.65775709, 84.65260905, 68.23679112, 85.9705011 , 14.02657588,
       83.26445495, 57.07785725, 97.94183394, 45.82563487, 13.28337728,
       16.0124728 , 14.57388161, 90.58165352, 37.88407458, 25.80008815,
       38.8546258 , 25.30950235, 38.2356834 , 24.63343215, 23.31527947,
       59.02000795, 56.17913439, 33.25918655, 61.98899466, 27.96421578,
       17.11356682, 99.51226871, 49.39188364, 39.77012808, 12.47758434,
       53.37119173, 73.50330216, 55.4271969 , 22.42396483, 99.29820904,
        1.84951116, 84.85298283, 14.90812887, 95.06014369, 36.03206202,
       52.14156808, 68.05720454,  1.21402889, 89.86528033, 36.57953509,
       47.18764296, 11.65577574, 23.78921961, 79.14254773, 67.46081976,
       74.50944497, 83.61556326, 80.2521031 , 90.12539821, 31.46551814,
       47.78815673, 61.86321692, 24.84283411, 79.60213917, 10.99242857,
       79.64196064,  2.70394632, 32.89715998,  2.73474798, 72.02340153,
       55.10459697, 32.0513397 , 54.14450429, 26.70980207,  3.96563685,
       84.18400411, 68.14143312, 55.7617435 , 82.34398212,  9.35178032,
        2.10579034, 18.58531299, 98.36688761, 70.24984582, 32.30693209,
       71.32314708, 18.95523284, 43.25348656, 36.3889089 , 32.23461734,
       13.142634  , 86.1993344 , 78.53662939, 15.24213672, 38.98378452,
       48.60234505, 28.14822429, 54.70569269, 26.1317855 ,  7.96957338,
       30.68144559, 64.89522268, 54.09474844, 95.31680953, 20.92971479,
       25.31676459, 46.00660779, 90.9349597 , 55.03760628, 21.29430566,
        1.62555482, 67.68698368, 62.43851186, 33.54262783, 80.87768608,
       76.13761652, 92.55505392, 73.80551724, 19.84812195, 29.08481689,
       37.7251295 , 36.23456628, 31.93048775, 77.64538192, 87.34264856,
       94.64934051, 33.24177361, 67.67677321, 12.08962295, 59.75446746,
       70.01351738, 33.41951807, 93.97563324, 57.13352923,  1.42497662,
       92.43925501, 31.47457604, 32.49829179, 24.85881772, 45.01157504,
       45.458759  , 49.36667793,  2.25843248, 18.78120062, 34.20293701,
       98.25154743, 96.91939562, 74.03075367, 90.98638336, 42.4886961 ,
       64.00853726, 33.71391309, 72.75930217, 54.98442475, 26.30560468,
       74.19185124, 47.86068231, 79.18971368, 42.82796171, 30.41436118,
       14.40694012, 84.07832635,  6.21116479, 52.29705891, 66.27243488,
       26.98671049,  4.22359709, 90.31081171, 72.34724471, 12.10802447,
        7.25776168, 17.85937776, 26.58361348, 49.41359277, 91.25253714,
       43.26965154, 27.28771305, 49.04723459, 92.75316205, 48.9229006 ,
       89.56693603, 16.99714309, 30.69728979, 78.00373642, 83.31629045,
       46.92012684, 13.24877979, 89.64007704, 94.41559472, 62.2851492 ,
       36.82627574,  5.66853767, 94.10361024, 63.28633591, 41.63318743,
       76.77071394, 85.12807138, 36.04858383, 98.99570426, 28.34670568,
       74.53856295, 51.36676754, 70.59463147, 50.13750892, 14.74073353,
       26.05313851, 78.7643836 , 77.18278029, 69.41193819, 56.40419245,
       41.84541963, 45.16203541,  8.73073761, 35.89328324, 19.33120037,
       82.56294216, 66.60886504, 59.70706911, 34.48397474, 40.85942711,
       42.87025668, 68.25662832, 69.27663781, 13.87920406, 19.24054789,
       56.18888223, 64.30537988, 68.9790901 , 33.57732084, 88.93734428,
       19.44806706, 35.63294138, 10.41277689, 74.75128177, 96.46184346,
       58.07273168, 35.76124017,  4.84029497, 98.77458561, 16.39847526,
       27.94966052, 67.45163132, 30.50065293,  6.95620328, 58.84697345,
       25.89999317, 76.71607167, 50.56463832, 43.33823829, 14.0972668 ,
       60.82111986, 92.31829143, 20.8059892 , 93.71331714, 13.97931736,
       30.94369751,  5.659824  , 70.01763747, 88.11700693,  7.84302602,
       42.09256659, 77.11457298, 18.51970309, 35.96249579, 38.36181541,
       27.13220726, 95.60664534,  9.5877451 , 57.80249077, 46.93737817,
       66.24843424, 90.71279007, 39.63622494, 26.25131747, 98.64933409,
       64.92148847, 16.27386868, 85.58149479, 23.05285493, 33.22347649,
       20.8923648 ,  8.86584198, 28.21123671, 61.49534933, 91.79134323,
       97.56011192, 31.03205969, 49.05427374, 56.66878301, 87.65272702,
       95.35249948,  8.78324161, 25.01734707, 47.41605203, 75.85648038,
       52.79186614, 88.00685586, 95.10844904, 87.75364088,  3.79461822,
       89.08557897, 65.99595533, 75.52361511, 61.67341715, 89.82647521,
       13.52819105, 66.27270749, 61.1392181 , 29.64108876, 52.44299859,
       69.28410138, 81.6468763 , 41.57567741, 83.90677664, 44.03081061,
       94.33476443, 17.2660121 , 86.45654403, 41.25981957, 94.83563106,
       26.67673002, 57.48613225, 70.40154927, 38.93456392, 90.70901805,
       86.92417352, 72.72237336, 44.08931417, 97.49401145, 37.40907777,
       46.27151205, 47.32727876, 78.73546785, 96.01037244, 10.50337005,
       36.46925175, 12.93301564, 82.04678338, 25.18746885, 36.58009661,
        2.06196542, 91.33249808, 17.05510506, 94.40174103,  5.7697897 ,
       84.01625293, 75.23680371, 10.23871399, 50.0913531 ,  4.60762992,
       18.5594135 , 56.28750231, 25.16782177, 56.85267186, 82.08222378,
       99.00566788, 21.84724653, 27.68337398, 40.49880956, 56.47479455,
       97.71237952, 18.79226167, 95.44840808, 46.50250668, 69.77733307,
       31.34738204, 38.56947367, 73.23718088, 63.14463991, 68.58381583,
        1.50201555, 50.6386143 , 94.21822272,  8.05576574, 76.22050466,
       77.04488283, 34.6559574 , 96.04322935, 98.91606768, 28.83135795,
       57.93330691, 10.96971929, 83.44731102, 98.90324493, 85.62208091,
       74.73507183, 83.98652392, 86.82677175,  2.96605131, 82.04910396,
       87.65806528, 66.50234438, 23.65353323, 80.40844288, 64.74499702,
       50.66397018, 46.54392961,  1.41523312, 32.13619051, 33.28295797,
       92.70066754, 17.69643286, 74.62561626, 82.34269545, 95.64879852,
       32.94126664, 59.01450481, 83.23636552,  9.93107869, 68.16173328,
       73.35947697, 64.42221967, 46.52322668, 99.03638972, 80.52221481,
       31.55865462, 98.31615427, 36.23972926, 80.95724314, 22.01311095,
       73.37342508, 65.6317826 , 52.90695003, 89.35870961,  7.24432611,
       30.37095123, 81.41824509, 85.55147573, 81.10007167, 37.49414986,
       91.69472669,  1.92708764, 32.97014603, 72.79632838, 79.84817327,
       83.79755914, 35.91162126, 70.19968365,  1.40771167,  2.65354304,
       17.01885104, 71.92404391, 91.34641827, 12.42778329, 79.10967704,
       89.24599423, 41.50125406, 70.19107748, 87.58377654, 96.69259216,
       52.29880771, 95.40546573, 10.40261397, 60.02410847, 49.32670597,
       27.8649231 , 67.29324159, 74.72243843, 72.92580516, 46.90323632,
       64.29977842, 27.06248373, 50.80334163, 82.67585125, 56.9458743 ,
        3.58641711, 37.27528289,  4.86445638, 35.87563473, 70.44950979,
       14.56999677, 58.97229271, 94.91403271, 60.16166312, 12.35403011,
       69.26325807, 67.17192284, 81.5397692 , 38.35645573, 77.87724068,
       43.76968419, 83.12984757, 57.22721382, 11.53455512,  4.58123753,
       10.6163911 ,  9.85819831, 86.60395309,  5.32243663, 83.91893663,
       13.5125143 , 27.79377745, 32.17795987, 70.89722832, 89.89367147,
       95.52043797, 39.59313981, 62.23863915, 74.65806585, 61.48084033,
       95.84506206, 61.81972714, 34.30978976, 49.90111104, 99.02463071,
       47.8198339 , 81.14101219, 72.19608719,  2.30042712, 83.55337606,
        2.9000305 , 37.95889879, 95.08653461, 53.30828866, 41.27411267,
       51.0490773 , 26.18766247, 76.20234889, 91.24403796, 36.34422856,
       95.30558686, 29.20200223, 72.0069987 , 32.83214832, 90.8763149 ,
       97.68771074, 75.61120787, 88.05922022, 74.47863119, 15.81508043,
       10.06777519, 72.94955724, 29.46801412, 11.81460839, 16.70842281,
       14.3210137 , 28.42933214, 81.99016658, 30.05807777, 88.05484433,
       81.53015215, 51.69922344, 41.84940438, 16.84816394, 44.86630377,
       71.69267224, 53.99416897,  2.78519056,  8.02902831, 16.98587688,
       53.71173692, 18.32954332, 45.35087082,  6.8209036 , 31.1620939 ,
       32.28713749, 21.121487  , 39.94830762, 42.06693499, 11.49066996])

In [ ]:
#Agregamos una columna incorrecta
estudiantes["incorrecta"]=0
estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Score Chemistry,incorrecta
0,female,group B,bachelor's degree,standard,none,72,72,74,20,0
1,female,group C,some college,standard,completed,69,90,88,90,0
2,female,group B,master's degree,standard,none,90,95,93,82,0
3,male,group A,associate's degree,free/reduced,none,47,57,44,88,0
4,male,group C,some college,standard,none,76,78,75,59,0
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,98,0
996,male,group C,high school,free/reduced,none,62,55,55,24,0
997,female,group C,high school,free/reduced,completed,59,71,65,12,0
998,female,group D,some college,standard,completed,68,78,77,46,0
999,female,group D,some college,free/reduced,none,77,86,86,71,0

In [ ]:
estudiantes.drop(columns=["incorrecta"])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Score Chemistry
0,female,group B,bachelor's degree,standard,none,72,72,74,20
1,female,group C,some college,standard,completed,69,90,88,90
2,female,group B,master's degree,standard,none,90,95,93,82
3,male,group A,associate's degree,free/reduced,none,47,57,44,88
4,male,group C,some college,standard,none,76,78,75,59
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,98
996,male,group C,high school,free/reduced,none,62,55,55,24
997,female,group C,high school,free/reduced,completed,59,71,65,12
998,female,group D,some college,standard,completed,68,78,77,46
999,female,group D,some college,free/reduced,none,77,86,86,71

In [ ]:
estudiantes=estudiantes.drop(columns=["incorrecta"])

In [ ]:
estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Score Chemistry
0,female,group B,bachelor's degree,standard,none,72,72,74,20
1,female,group C,some college,standard,completed,69,90,88,90
2,female,group B,master's degree,standard,none,90,95,93,82
3,male,group A,associate's degree,free/reduced,none,47,57,44,88
4,male,group C,some college,standard,none,76,78,75,59
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,98
996,male,group C,high school,free/reduced,none,62,55,55,24
997,female,group C,high school,free/reduced,completed,59,71,65,12
998,female,group D,some college,standard,completed,68,78,77,46
999,female,group D,some college,free/reduced,none,77,86,86,71